// LexLens — PDF content verification (PRD §41).
// Downloads a session-scoped PDF for the India test notice and scans the text.
// Run: node scripts/test-pdf.mjs  [dev server running]
import { writeFileSync } from "node:fs";
import { execSync } from "node:child_process";

const BASE = "http://localhost:3000";
const jar = { cookie: "" };
async function req(method, path, body) {
  const res = await fetch(`${BASE}${path}`, {
    method,
    headers: { ...(body ? { "Content-Type": "application/json" } : {}), ...(jar.cookie ? { Cookie: jar.cookie } : {}) },
    body: body ? JSON.stringify(body) : undefined,
  });
  const sc = res.headers.get("set-cookie");
  if (sc) jar.cookie = sc.split(";")[0];
  return res;
}

const NOTICE = `BY REGISTERED POST A.D.

Date: 18 September 2026

To, Mr. Rohan Mehta, Mumbai.

SUB: LEGAL NOTICE UNDER SECTION 138 OF THE NEGOTIABLE INSTRUMENTS ACT, 1881

You issued Cheque No. 458721 dated 5 September 2026 for Rs. 85,000 drawn on State Bank of India, which was dishonoured on 10 September 2026. Pay Rs. 85,000 within 15 days of receipt of this notice, failing which criminal proceedings under Section 138 will follow. This notice was received under acknowledgment on 19 September 2026.`;

await req("GET", "/api/notices");
const up = await (await req("POST", "/api/notices", { text: NOTICE, label: "PDF verify", source: "paste" })).json();
await req("POST", `/api/notices/${up.notice.id}/analyze`, {});
await new Promise((r) => setTimeout(r, 15000));
const pdf = await req("GET", `/api/notices/${up.notice.id}/pdf`);
const buf = Buffer.from(await pdf.arrayBuffer());
writeFileSync("/tmp/lexlens-test.pdf", buf);
console.log(`PDF: ${pdf.status}, ${buf.length} bytes, content-type ${pdf.headers.get("content-type")}`);

execSync("pdftotext /tmp/lexlens-test.pdf /tmp/lexlens-test.txt");
const text = execSync("cat /tmp/lexlens-test.txt").toString();

let pass = 0, fail = 0;
const must = (name, cond) => { if (cond) { pass++; console.log(`  ✓ ${name}`); } else { fail++; console.error(`  ✗ ${name}`); } };

for (const bad of ["FDCPA", "1692", "CPLR", "garnishment", "bank levy", "30-day dispute"]) {
  must(`PDF excludes "${bad}"`, !new RegExp(bad, "i").test(text));
}
must("PDF excludes technical names", !/glm|provider|fastapi|postgresql|node\.js/i.test(text));
must("PDF includes §138", /138/.test(text));
must("PDF includes the amount", /85,000|85000/.test(text));
must("PDF includes the deadline 2026-10-04 (4 Oct 2026)", /2026-10-04|4 Oct 2026|04 Oct 2026/.test(text));
must("PDF includes receipt date 19 September / 2026-09-19", /19 Sep|2026-09-19|19\/09/.test(text));
must("PDF branded Generated by LexLens", /Generated by LexLens|LexLens/i.test(text));

console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail > 0 ? 1 : 0);
